name: "JFrog-GitHub NPM Publish OIDC Integration"
on: push


# This is required as per below link
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write

jobs:
  build:
     runs-on: ubuntu-latest
     env:
      OIDC_PROVIDER: 'nareshgithub'
      PLATFORM_REPO: 'blr-npm-oidc-virtual'
     defaults:
      run:
        working-directory: ./package
     steps:
       - name: Checkout
         uses: actions/checkout@v3
              
       - name: Setup Node npm
         uses: actions/setup-node@v3
   
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v3
         env:  
           JF_URL: ${{ secrets.JF_URL }}
         with:
           oidc-provider-name: ${{ env.OIDC_PROVIDER }}
           
       - name: Run Audit scan for the git workspace
         run: jf audit .

       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=$PLATFORM_REPO --repo-deploy=$PLATFORM_REPO

           
       - name: Install Dependencies
         run: jf npm install --registry https://registry.npmjs.org --build-name="naresh-npm-xray" --build-number=${{ github.run_number }}

       - name: audit
         run: jf npm audit
           
       - name: Run tests
         run: npm test
         
       - name: Publish
         run: jf npm publish --build-name="naresh-npm-xray" --build-number=${{ github.run_number }}
         
       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env naresh-npm-xray ${{ github.run_number }}
          # Collect VCS details from git and add them to the build
          jf rt build-add-git naresh-npm-xray ${{ github.run_number }}
          # Publish build info 
          jf rt build-publish naresh-npm-xray ${{ github.run_number }}

       - name: Run build scan
         run: jf rt build-scan naresh-npm-xray ${{ github.run_number }}
